name: "Habit Tracker"
description: "A simple Python/Flask habit tracker with SQLite storage"
version: "1.0.6"
slug: "habit_tracker"
arch:
  - aarch64
  - amd64
  - armv7
init: false
options: {}
schema: {}
ingress: true  # This allows you to view the UI inside the HA sidebar
ingress_port: 5000